local UAVIONIX_ADSB_OUT_CFG_REGISTRATION = {}
UAVIONIX_ADSB_OUT_CFG_REGISTRATION.id = 10004
UAVIONIX_ADSB_OUT_CFG_REGISTRATION.crc_extra = 133
UAVIONIX_ADSB_OUT_CFG_REGISTRATION.fields = {
             { "registration", "<c9" },
             }
return UAVIONIX_ADSB_OUT_CFG_REGISTRATION
