local UAVIONIX_ADSB_TRANSCEIVER_HEALTH_REPORT = {}
UAVIONIX_ADSB_TRANSCEIVER_HEALTH_REPORT.id = 10003
UAVIONIX_ADSB_TRANSCEIVER_HEALTH_REPORT.crc_extra = 4
UAVIONIX_ADSB_TRANSCEIVER_HEALTH_REPORT.fields = {
             { "rfHealth", "<B" },
             }
return UAVIONIX_ADSB_TRANSCEIVER_HEALTH_REPORT
